### ISSUE TITLE
Axios does not handle nested param objects nicely

### ISSUE THREAD

**Issue by kwf37** [Do-Stuff-Club/expense_tracker_web#1]
Seen in `redux/tags/action.ts`, Axios requires extra configuration to serialize the params properly. Perhaps I should switch to `fetch` instead? See this Axios issue for more info: https://github.com/axios/axios/issues/738

**Comment by edward93** [comment]
This is fixed, I think by the very recent PR

**Comment by kwf37** [comment]
o nice

**Comment by kwf37** [comment]
Nvm this only applies to GET reqs, and is causing me issues again now that the axios interceptor thing is removed.

**Comment by kwf37** [comment]
Switched to fetch API instead of Axios
